/*
 * Ory APIs
 *
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * API version: latest
 * Contact: support@ory.sh
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ProjectNext struct for ProjectNext
type ProjectNext struct {
	Id string `json:"id"`
	// The name of the project.
	Name *string `json:"name,omitempty"`
	RevisionId string `json:"revision_id"`
	Services ProjectServices `json:"services"`
	// The project's slug
	Slug string `json:"slug"`
	// The state of the project.
	State string `json:"state"`
}

// NewProjectNext instantiates a new ProjectNext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectNext(id string, revisionId string, services ProjectServices, slug string, state string) *ProjectNext {
	this := ProjectNext{}
	this.Id = id
	this.RevisionId = revisionId
	this.Services = services
	this.Slug = slug
	this.State = state
	return &this
}

// NewProjectNextWithDefaults instantiates a new ProjectNext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectNextWithDefaults() *ProjectNext {
	this := ProjectNext{}
	return &this
}

// GetId returns the Id field value
func (o *ProjectNext) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectNext) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectNext) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectNext) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectNext) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectNext) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectNext) SetName(v string) {
	o.Name = &v
}

// GetRevisionId returns the RevisionId field value
func (o *ProjectNext) GetRevisionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RevisionId
}

// GetRevisionIdOk returns a tuple with the RevisionId field value
// and a boolean to check if the value has been set.
func (o *ProjectNext) GetRevisionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RevisionId, true
}

// SetRevisionId sets field value
func (o *ProjectNext) SetRevisionId(v string) {
	o.RevisionId = v
}

// GetServices returns the Services field value
func (o *ProjectNext) GetServices() ProjectServices {
	if o == nil {
		var ret ProjectServices
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
func (o *ProjectNext) GetServicesOk() (*ProjectServices, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Services, true
}

// SetServices sets field value
func (o *ProjectNext) SetServices(v ProjectServices) {
	o.Services = v
}

// GetSlug returns the Slug field value
func (o *ProjectNext) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ProjectNext) GetSlugOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ProjectNext) SetSlug(v string) {
	o.Slug = v
}

// GetState returns the State field value
func (o *ProjectNext) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ProjectNext) GetStateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ProjectNext) SetState(v string) {
	o.State = v
}

func (o ProjectNext) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["revision_id"] = o.RevisionId
	}
	if true {
		toSerialize["services"] = o.Services
	}
	if true {
		toSerialize["slug"] = o.Slug
	}
	if true {
		toSerialize["state"] = o.State
	}
	return json.Marshal(toSerialize)
}

type NullableProjectNext struct {
	value *ProjectNext
	isSet bool
}

func (v NullableProjectNext) Get() *ProjectNext {
	return v.value
}

func (v *NullableProjectNext) Set(val *ProjectNext) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectNext) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectNext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectNext(val *ProjectNext) *NullableProjectNext {
	return &NullableProjectNext{value: val, isSet: true}
}

func (v NullableProjectNext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectNext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


