/*
 * Ory APIs
 *
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * API version: latest
 * Contact: support@ory.sh
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CreateProjectApiTokenRequest struct for CreateProjectApiTokenRequest
type CreateProjectApiTokenRequest struct {
	// The Token Name  A descriptive name for the token.  in: body
	Name string `json:"name"`
}

// NewCreateProjectApiTokenRequest instantiates a new CreateProjectApiTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectApiTokenRequest(name string) *CreateProjectApiTokenRequest {
	this := CreateProjectApiTokenRequest{}
	this.Name = name
	return &this
}

// NewCreateProjectApiTokenRequestWithDefaults instantiates a new CreateProjectApiTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectApiTokenRequestWithDefaults() *CreateProjectApiTokenRequest {
	this := CreateProjectApiTokenRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateProjectApiTokenRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateProjectApiTokenRequest) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateProjectApiTokenRequest) SetName(v string) {
	o.Name = v
}

func (o CreateProjectApiTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateProjectApiTokenRequest struct {
	value *CreateProjectApiTokenRequest
	isSet bool
}

func (v NullableCreateProjectApiTokenRequest) Get() *CreateProjectApiTokenRequest {
	return v.value
}

func (v *NullableCreateProjectApiTokenRequest) Set(val *CreateProjectApiTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectApiTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectApiTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectApiTokenRequest(val *CreateProjectApiTokenRequest) *NullableCreateProjectApiTokenRequest {
	return &NullableCreateProjectApiTokenRequest{value: val, isSet: true}
}

func (v NullableCreateProjectApiTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectApiTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


